-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(c7b3f3)",
			inactive_border = "rgb(4e4570)",
		},
	},
	group = {
		col = {
			border_active = "rgb(c7b3f3)",
			border_inactive = "rgb(4e4570)",
			border_locked_active = "rgb(e53935)",
			border_locked_inactive = "rgb(4e4570)",
		},
		groupbar = {
			col = {
				active = "rgb(c7b3f3)",
				inactive = "rgb(4e4570)",
				locked_active = "rgb(e53935)",
				locked_inactive = "rgb(4e4570)",
			},
		},
	},
})
