[colors.primary]
background = '#ffffff'
foreground = '#020007'

[colors.selection]
text = '#020007'
background = '#ece6ff'

[colors.cursor]
text = '#ffffff'
cursor = '#c7b3f3'

[colors.normal]
black   = '#1F1F28'
red     = '#e65c78'
green   = '#3fb659'
yellow  = '#ffcd3f'
blue    = '#ceb8ff'
magenta = '#f0e9ff'
cyan    = '#c7b3f3'
white   = '#424144'

[colors.bright]
black   = '#010004'
red     = '#ff7f99'
green   = '#72ff90'
yellow  = '#ffd04c'
blue    = '#ccb5ff'
magenta = '#f0e9ff'
cyan    = '#e7ddff'
white   = '#fbf9ff'
