cursor #020007
cursor_text_color #2a243f

foreground            #020007
background            #ffffff
selection_foreground  #020007
selection_background  #c7b3f3
url_color             #c7b3f3

color0   #1F1F28
color1   #e65c78
color2   #3fb659
color3   #ffcd3f
color4   #ceb8ff
color5   #f0e9ff
color6   #c7b3f3
color7   #424144
color8   #010004
color9   #ff7f99
color10  #72ff90
color11  #ffd04c
color12  #ccb5ff
color13  #f0e9ff
color14  #e7ddff
color15  #fbf9ff
